-- MySQL Script generated by MySQL Workbench
-- Thứ tư, 07 Tháng hai Năm 2018 10:04:52 ICT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema Minato
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Minato
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Minato` DEFAULT CHARACTER SET latin1 ;
USE `Minato` ;

-- -----------------------------------------------------
-- Table `Minato`.`airlines`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Minato`.`airlines` (
  `code` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  `other_details` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`code`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `Minato`.`customers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Minato`.`customers` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `customer_name` VARCHAR(255) NULL DEFAULT NULL,
  `other_details` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `Minato`.`filght_schedules`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Minato`.`filght_schedules` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `arrival_time` DATETIME NULL DEFAULT NULL,
  `departure_time` DATETIME NULL DEFAULT NULL,
  `flight_number` INT(11) NOT NULL,
  `other_details` VARCHAR(255) NULL DEFAULT NULL,
  `airline_code` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FKsfmj8ytu8dl4vjsugc1w5qpr5` (`airline_code` ASC),
  CONSTRAINT `FKsfmj8ytu8dl4vjsugc1w5qpr5`
    FOREIGN KEY (`airline_code`)
    REFERENCES `Minato`.`airlines` (`code`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `Minato`.`ref_classes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Minato`.`ref_classes` (
  `class_number` INT(11) NOT NULL AUTO_INCREMENT,
  `class_number_description` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`class_number`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `Minato`.`ref_payment_methods`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Minato`.`ref_payment_methods` (
  `code` INT(11) NOT NULL AUTO_INCREMENT,
  `payment_method_description` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`code`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `Minato`.`ref_reservation_status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Minato`.`ref_reservation_status` (
  `code` INT(11) NOT NULL AUTO_INCREMENT,
  `reservatrion_status_desciption` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`code`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `Minato`.`reservations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Minato`.`reservations` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `customer_name` VARCHAR(255) NULL DEFAULT NULL,
  `date_of_flight` DATETIME NULL DEFAULT NULL,
  `date_reservation_made` DATETIME NULL DEFAULT NULL,
  `e_ticket_number` INT(11) NOT NULL,
  `other_details` VARCHAR(255) NULL DEFAULT NULL,
  `customer_id` INT(11) NULL DEFAULT NULL,
  `schedule_id` INT(11) NULL DEFAULT NULL,
  `class_number` INT(11) NULL DEFAULT NULL,
  `payment_method_code` INT(11) NULL DEFAULT NULL,
  `reservatrion_status_code` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK8eccffekcj27jkdiyw2e9r8ks` (`customer_id` ASC),
  INDEX `FK8cqfssn35ubhiyxl5sgpd1e9c` (`schedule_id` ASC),
  INDEX `FKfj217i8eq60ca4twql77d4cbd` (`class_number` ASC),
  INDEX `FK320tjktet2rmnt3q4h1rhlboa` (`payment_method_code` ASC),
  INDEX `FKruntg97bvjh1bhyec8cs1nuh9` (`reservatrion_status_code` ASC),
  CONSTRAINT `FK320tjktet2rmnt3q4h1rhlboa`
    FOREIGN KEY (`payment_method_code`)
    REFERENCES `Minato`.`ref_payment_methods` (`code`),
  CONSTRAINT `FK8cqfssn35ubhiyxl5sgpd1e9c`
    FOREIGN KEY (`schedule_id`)
    REFERENCES `Minato`.`filght_schedules` (`id`),
  CONSTRAINT `FK8eccffekcj27jkdiyw2e9r8ks`
    FOREIGN KEY (`customer_id`)
    REFERENCES `Minato`.`customers` (`id`),
  CONSTRAINT `FKfj217i8eq60ca4twql77d4cbd`
    FOREIGN KEY (`class_number`)
    REFERENCES `Minato`.`ref_classes` (`class_number`),
  CONSTRAINT `FKruntg97bvjh1bhyec8cs1nuh9`
    FOREIGN KEY (`reservatrion_status_code`)
    REFERENCES `Minato`.`ref_reservation_status` (`code`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
